version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: iqa-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: iqa_user
      POSTGRES_PASSWORD: iqa_secret_2024
      POSTGRES_DB: ibrahim_quran_academy
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: iqa-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
