export const pricingPlans = [
  {
    id: "starter",
    name: "Starter",
    description: "Perfect for trying out",
    price: 60,
    currency: "USD",
    period: "month",
    sessions: 4,
    duration: "45 min each",
    features: [
      "4 sessions per month",
      "45 minutes per session",
      "Personalized curriculum",
      "Progress tracking",
      "WhatsApp support",
    ],
    popular: false,
  },
  {
    id: "standard",
    name: "Standard",
    description: "Most popular choice",
    price: 100,
    currency: "USD",
    period: "month",
    sessions: 8,
    duration: "45 min each",
    features: [
      "8 sessions per month",
      "45 minutes per session",
      "Personalized curriculum",
      "Progress tracking",
      "WhatsApp support",
      "Monthly progress report",
      "Homework and practice materials",
    ],
    popular: true,
  },
  {
    id: "premium",
    name: "Premium",
    description: "For serious learners",
    price: 140,
    currency: "USD",
    period: "month",
    sessions: 12,
    duration: "45 min each",
    features: [
      "12 sessions per month",
      "45 minutes per session",
      "Personalized curriculum",
      "Progress tracking",
      "Priority WhatsApp support",
      "Weekly progress report",
      "Homework and practice materials",
      "Flexible rescheduling",
    ],
    popular: false,
  },
];
